### ISSUE TITLE
m1 맥북의 아이폰 시뮬레이터에서 실행이 되지 않습니다.

### ISSUE THREAD

**Issue by mangofever** [navermaps/NMapsMap#17]
실행이 가능하도록, 부탁드립니다.

**Comment by beggu84** [comment]
다음 버전(3.15.0)에 XCFramework 로 배포될 예정입니다. 그 이후에도 문제가 있으면 Naver Cloud Platform 에 정식 문의 넣어주세요.

**Comment by mangofever** [comment]
답변 고맙습니다~ 이후에는 알려주신 곳에 문의 하겠습니다.
그런데 혹시 3.15.0은 언제쯤 릴리즈 예정인지 알 수 있을까요?

**Comment by beggu84** [comment]
3.15.0 버전 배포는 약 3-4주 후로 예상됩니다.

**Comment by mangofever** [comment]
> XCFramework 로 변경한 지 하루이틀 밖에 되지 않아서 내부적으로 충분히 테스트 하고 약 3-4주 후에 3.15.0 버전 배포에 포함될 예정입니다.

고맙습니다~!

**Comment by wookeon** [comment]
아 업데이트 예정이라니 다행이네요. 감사합니다~

**Comment by wookeon** [comment]
@beggu84 
어제 3.15.0 가 릴리즈 되었는데, 말씀하신 xcframework 배포 일정은 미뤄졌나요?
