### ISSUE TITLE
Carthage를 공식적으로 지원하실 계획이 있는지 궁금합니다.

### ISSUE THREAD

**Issue by stleamist** [navermaps/NMapsMap#2]
패키지 매니저로 CocoaPods보다 [Carthage](https://github.com/Carthage/Carthage)를 선호해서 [직접 GitHub Releases를 링크한 JSON을 만들어 사용하는 방법](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification)으로 Carthage에서 프레임워크를 쓰고 있는데요.
Git LFS를 사용하는 3.3.0 버전부터는 자동으로 생성되는 릴리즈 아카이브 ZIP에 `NMapsMap` 바이너리 파일이 포함되지 않아 이 방법의 사용이 힘들어졌습니다.

[제 리포지터리](https://github.com/stleamist/NMapsMap/releases/tag/release%2F3.3.0)와 같이 `git archive` 명령으로 아카이브한 파일을 `NMapsMap.framework.zip` 파일명으로 Release Assets에 업로드하는 것만으로 바이너리 프레임워크의 Carthage 지원이 가능한데, 공식적인 Carthage 지원이나, GitHub Releases에 NMapsMap 바이너리가 포함된 아카이브를 업로드할 계획이 있으신지 궁금합니다.

**Comment by garoad** [comment]
@stleamist 
안녕하세요 요청하신대로 zip으로 압축한 바이너리 태그에 첨부했습니다. 다음 배포부터 계속 지원하도록 하겠습니다.
감사합니다.

**Comment by stleamist** [comment]
@garoad 방금 확인해봤는데 이제 잘 되네요. ㅎㅎ 감사합니다!

**Comment by stleamist** [comment]
@garoad 3.4.0 버전도 아카이브 릴리즈 부탁드립니다. 😢

**Comment by garoad** [comment]
> @garoad 3.4.0 버전도 아카이브 릴리즈 부탁드립니다. 😢

죄송합니다. 깜빡했네요 업로드했으니 확인 부탁드립니다.

**Comment by stleamist** [comment]
3.4.0, 3.5.0 버전 모두 Carthage로 빌드 시 다음과 같은 오류가 발생하며 빌드가 진행되지 않습니다. 
`Dependency "NMapsMap" has no shared framework schemes for any of the platforms: iOS`

포크해서 테스트해보니 릴리즈에 업로드된 파일 이름이 정확히 `*.framework.zip`으로 끝날 때만 정상적으로 작동하는 것 같네요. 😭😭

**Comment by garoad** [comment]
> 3.4.0, 3.5.0 버전 모두 Carthage로 빌드 시 다음과 같은 오류가 발생하며 빌드가 진행되지 않습니다.
> `Dependency "NMapsMap" has no shared framework schemes for any of the platforms: iOS`
> 
> 포크해서 테스트해보니 릴리즈에 업로드된 파일 이름이 정확히 `*.framework.zip`으로 끝날 때만 정상적으로 작동하는 것 같네요. 😭😭

파일명 수정해놨습니다.

**Comment by stleamist** [comment]
@garoad 잘 작동하네요. 감사합니다!
