### ISSUE TITLE
사용자의 현재 위치 접근 권한

### ISSUE THREAD

**Issue by leechoohyoung** [navermaps/NMapsMap#3]
nmapsmap 3.3.0 을 사용중입니다.

위 버전을 사용해서 애플 심사 신청시 아래와 같은 이슈가 검출됩니다.
이슈의 내용은 앱의 Info.plist 파일에 NSLocationAlwaysUsageDescription 문구를 추가해야 한다는 것인데, 현재 저희 앱에서는 서비스의 특성상 NSLocationWhenInUseUsageDescription 문구만 사용해야 합니다.
그러므로 nmapsmap 에서 CLLocationManager 사용시 requestWhenInUseAuthorization 메소드로 권한을 요청하도록 수정을 요청합니다.

> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by garoad** [comment]
@leechoohyoung 3.4.0 버전에 적용했습니다. 업데이트하시고 확인 부탁드립니다.
감사합니다.
